lib/record_store/zone.rb, test/zone_test.rb
I am not sure if this is part of the DNS standard, or whether this is a limitation of just DynECT. But I think it makes sense to enforce this anyway.
Fixes #5. For review: @es and @andrewlouis93
=> Validates that all records with matching FQDN and type share the same TTL

lib/record_store/provider/dnsimple.rb, lib/record_store/provider/dynect.rb, lib/record_store/record.rb, lib/record_store/record/alias.rb, test/providers/dnsimple_test.rb, test/providers/dynect_test.rb, test/zone_test.rb
Makes Record::ALIAS use the alias attribute instead of the cname attribute. 
@es @sbfaulkner
=> Make Record::ALIAS use the alias attribute

bin/console, lib/record_store/changeset.rb, lib/record_store/cli.rb, lib/record_store/provider.rb, lib/record_store/provider/dnsimple.rb, lib/record_store/provider/dynect.rb, lib/record_store/record.rb, lib/record_store/zone.rb, lib/record_store/zone/config.rb, lib/record_store/zone/yaml_definitions.rb, test/changeset_test.rb, test/dummy/config.yml, test/dummy/zones/empty.com.yml, test/dummy/zones/merged-records.com.yml, test/dummy/zones/one-record.com.yml, test/dummy/zones/two-providers.com.yml, test/dummy/zones/two-records.com.yml, test/dummy/zones/zone-file.com.yml, test/providers/dnsimple_test.rb, test/providers/dynect_test.rb, test/test_helper.rb, test/zone/config_test.rb, test/zone_test.rb
For: https://github.com/Shopify/service-disruptions/issues/530, https://github.com/Shopify/traffic/issues/998, https://github.com/Shopify/traffic/issues/169 
**Problem**:
Record Store currently only supports a single provider. This requires us to manually change the provider of every single zone and deploy.
**Solution**:
By deploying to multiple providers at all times, we can have a zone's NS records point to more than one (lowering the impact of a DNS provider outage). This PR adds the ability to specify multiple providers for a single zone. 
Before a zone would specify:
```
provider: DynECT
```
Now the config *must* be changed to an array format:
```
providers:
- DynECT
```
To have the zone synced to multiple providers at the same time, simply specify an additional provider in the …
=> Support multiple providers for individual zones

lib/record_store/provider/dnsimple.rb, test/providers/dnsimple_test.rb
Related: https://github.com/Shopify/record-store/issues/876
r: @klautcomputing @marc-barry
=> Fix DNSimple treating SRV attributes as strings

lib/record_store/changeset.rb, lib/record_store/provider/dnsimple.rb, template/zones/dnsimple.example.com.yml, template/zones/dynect.example.com.yml, test/changeset_test.rb
**Problem**:
When generating the changeset, record store lines up the desired and current records in 2 arrays (for every `{type, fqdn}`) and zips them. This gives us an array of pairs (current record and desired record). If the order of records changes, it's possible to generate updates that'll create duplicate records inflight. 
**Example**:
Suppose you have record `A` and `B` with matching FQDNs, different content, but matching TTLs. The change is to modify the TTL of both records, but we've also re-arranged them in record store.
Provider (aka current records): `[A_current, B_current]`
Record Store (aka desired records): `[B_desired, A_desired]`
The changeset produced will have the record id of `A_current` update to match `B_desired`. As the updates are applied, record store will …
=> TTL updates apply to same record

lib/record_store/provider/dnsimple.rb, lib/record_store/version.rb
**Problem**
DNSimple escapes semicolons even if they're already escaped. It then also esacpes the slash that's escaping the semicolon.
**Solution**
This remove the slash escaping the semicolon before we update the records in DNSimple. It'll also automatically escape any semicolons when reading the API to keep records in sync properly.
r: @dwradcliffe @stonith
=> Mimic DNSimple's behaviour around escaping semicolons

lib/record_store/record/alias.rb, lib/record_store/record/cname.rb, lib/record_store/version.rb, test/record_test.rb
Recently, https://github.com/Shopify/record-store/pull/1271 failed to deploy because of CNAME circular reference.
This PR will validate that this does not happen again.
=> Check for circular references in CNAME

lib/record_store/cli.rb, test/cli_test.rb
When we removed `record-store validate_all_present`, our CI continued to have this as a step and it didn't cause failures.
This made me realize Thor doesn't return a non-zero exit status when the command is unknown.
https://github.com/erikhuda/thor/issues/244#issuecomment-11116989
This probably breaks compatibility in a way, but I think it's fine. Should I ship a 4.1.0 with that?
@es @dwradcliffe
=> Return exit status 1 on failure

lib/record_store/provider/dynect.rb
We recently started to see errors such as 
```
/app/data/bundler/ruby/2.3.0/gems/fog-dynect-0.1.0/lib/fog/dynect/dns.rb:144:in `rescue in poll_job': Job 3822483214 is still incomplete (Fog::DNS::Dynect::JobIncomplete)
from /app/data/bundler/ruby/2.3.0/gems/fog-dynect-0.1.0/lib/fog/dynect/dns.rb:131:in `poll_job'
from /app/data/bundler/ruby/2.3.0/gems/fog-dynect-0.1.0/lib/fog/dynect/dns.rb:105:in `request'
```
during deploy. I suspect this is because now we have more entries in Dyn it takes more time for the job to finish in under 10 minutes(default polling timeout). The PR doubles the timeout.
@Shopify/traffic
=> bump up job polling timeout for fog-dynect

lib/record_store/record.rb, test/record_test.rb
Names such as `website--name.com` are valid domain names according to [this](https://stackoverflow.com/questions/16468309/can-domain-name-have-two-continuous-hyphens) but our CNAME_REGEX doesn't allow them. This PR permits said domain names.
=> Support double hyphen (--) in CNAME

lib/record_store/provider.rb, lib/record_store/version.rb
not sure why this has not previously been an issue, but this PR fixes this...
```
$ dev add_zone mruby.science
/Users/sbfaulkner/.gem/ruby/2.3.1/gems/record_store-4.0.3/lib/record_store/provider.rb:5:in `provider_for': uninitialized constant #<Class:RecordStore::Provider>::Resolv (NameError)
from /Users/sbfaulkner/.gem/ruby/2.3.1/gems/record_store-4.0.3/lib/record_store/cli.rb:125:in `download'
from /Users/sbfaulkner/.gem/ruby/2.3.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
from /Users/sbfaulkner/.gem/ruby/2.3.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
from /Users/sbfaulkner/.gem/ruby/2.3.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
from /Users/sbfaulkner/.gem/ruby/2.3.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
from …
```
=> require 'resolv' to fix uninitialized constant

lib/record_store/provider/dynect.rb, lib/record_store/version.rb, record_store.gemspec, test/fixtures/vcr_cassettes/dynect_apply_changeset_update.yml, test/providers/dynect_test.rb
this PR fixes #39
fog-dynect expects string keys for options hash (https://github.com/fog/fog-dynect/blob/master/lib/fog/dynect/requests/dns/put_record.rb#L19)
record_store was passing symbols (https://github.com/Shopify/record_store/pull/41/files#diff-f3285f7dfe4728480bd7d479256b9608L23)
this fixes that (and includes a test that verifies we actually update a specific record)
=> fix updates of records with same fqdn

Gemfile, Gemfile.lock, lib/record_store/provider/dnsimple.rb, lib/record_store/version.rb, template/secrets.json, test/dummy/secrets.json, test/fixtures/vcr_cassettes/dnsimple_apply_changeset.yml, test/fixtures/vcr_cassettes/dnsimple_apply_changeset_with_alias.yml, test/fixtures/vcr_cassettes/dnsimple_retrieve_current_records.yml, test/fixtures/vcr_cassettes/dnsimple_retrieve_current_records_no_alias.yml, test/fixtures/vcr_cassettes/dnsimple_zones.yml, test/providers/dnsimple_test.rb, test/test_helper.rb
`record_store` is currently using the DNSimple adapter from the `fog` gem. This adapter is quite old, it was extracted in 2016 into a `fog-dnsimple`.
Moreover, I've just released a new version of `fog-dnsimple` (fog/fog-dnsimple#3) that uses our API v2. API v1 are deprecated since 2016, and we are now in the process of shutting them down.
I need some help here to update the CircleCI integration to use the new auth mechanism (specifically an API v2 account token you can generate from the Shopify account, and the account ID). /cc @charlescng @es @sbfaulkner 
Technically speaking the client could fetch the ID from the token, but due to the way Fog is structured I decided to request it explicitly.
Unfortunately I was not able to run the integration specs locally because of the fixture …
=> Switch to fog-dnsimple and API v2

lib/record_store/cli.rb, lib/record_store/version.rb
This fixes (maybe) a bug where secrets are not decrypted when a rollback happens while executing `record-store validate_initial_state`.
@Shopify/edgescale
=> Decrypt secrets on rollback

lib/record_store/changeset.rb, lib/record_store/provider.rb, lib/record_store/provider/dynect.rb, lib/record_store/provider/google_cloud_dns.rb
I noticed that when the GoogleCloudDNS provider was used, that some of the progress messages were not produced.
The ones for specific operations (Removing/Creating/Updating) are not as simple, but this PR at least moves the Apply and Published output to the common function in the changeset that invokes the individual providers.
context: for dynect and dnsimple we have to actually apply the individual changes (which is what the base implementation of `apply_changeset` does... however, google never calls the base implementation and instead overrides it
=> Refactor for more consistent output

lib/record_store/record/spf.rb, lib/record_store/record/txt.rb, test/record_test.rb
this PR closes #42
SPF records are TXT records, so use Record::TXT as a superclass for the implementation
NOTE: as per https://tools.ietf.org/html/rfc7208#section-14.1 SPF records are deprecated
=> SPF refactor

README.md, lib/record_store/provider.rb, lib/record_store/provider/dnsimple.rb, lib/record_store/provider/dynect.rb
add/remove/update should not be public - they are not called except in the base `Provider#apply_changeset`
this PR makes them private and closes #43
=> refactor to make provider add/remove/update private

dev.yml, lib/record_store/provider/dnsimple.rb, lib/record_store/provider/dynect.rb, lib/record_store/provider/google_cloud_dns.rb, lib/record_store/record.rb, lib/record_store/record/txt.rb, test/providers/google_cloud_dns_test.rb, test/record_test.rb
this PR fixes #58
consistent handling of rdata for TXT records and escaping of `"` characters in strings
strip wrapping quotes from google API rdata
UPDATE: rebased after merging #55 #56 and #57
=> Txt record quoting and escaping

CHANGELOG.md, lib/record_store/version.rb
from CHANGELOG...
```
- Output progress messages for GoogleCloudDNS provider too. [BUGFIX]
- Fix quoting/escaping for TXT records. [BUGFIX]
- Make implementation-specific methods of Provider private. [REFACTOR]
- DRY up SPF support to use TXT superclass implementation. [REFACTOR]
```
=> bump to version 5.0.5 and update CHANGELOG

CHANGELOG.md, lib/record_store/provider/dynect.rb, lib/record_store/version.rb, lib/record_store/zone.rb
fog-dynect is not expecting to run with multiple threads sharing the dynect session, but that’s how record_store is using it
* fog-dynect issues a request and then if the response is  a 307 it polls the jobs api until the request is completed
* but… meanwhile another thread could have attempted to issue a request with the api
which means the code here... https://github.com/Shopify/record_store/blob/master/lib/record_store/zone.rb#L56
could cause us to thrash on the api
this PR attempts to address that by adding a mutex and syncronizing for exclusive session use
=> Use distinct Dynect sessions for each thread

.travis.yml
Move up to Ruby 2.4.3 to match the version used in dev.
=> Update CI Ruby version to match dev

lib/record_store/record.rb, lib/record_store/version.rb, test/record_test.rb
AWS Certificate Manager leverages DNS CNAME entries to verify ownership of domains for certificate issuance as noted at https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-validate-dns.html.  Although technically allowed, it is rare to see these in the hostname portion of CNAME entries.
@sbfaulkner @charlescng
=> Add support for underscores in hostname CNAME entries

CHANGELOG.md, lib/record_store/version.rb, lib/record_store/zone.rb, test/zone_test.rb
Removes validate_alias_points_to_root validation. ALIAS records are not only for apex root's.
ref: https://github.com/Shopify/record-store/pull/2484
=> remove alias-points-to-root validation

record_store.gemspec, test/cli_test.rb
this PR fixes tests to work with newer Thor gem
older versions were passing the wrong type to `Kernel#exit`
=> fix tests for newer thor

lib/record_store/provider/dnsimple.rb, lib/record_store/provider/dynect.rb, lib/record_store/provider/google_cloud_dns.rb, lib/record_store/record.rb, test/dummy/zones/mixed-case-fqdn.com.yml, test/dummy/zones/mixed-case-fqdn.com/TXT__Another.yml, test/providers/dnsimple_test.rb, test/providers/dynect_test.rb, test/providers/google_cloud_dns_test.rb, test/record_test.rb, test/zone_test.rb
BACKGROUND:
* DNS is case-insenstive
* record-store is (was?) case sensitive
* DNSimple does not allow creation of DNS records with Mixed-Case fqdns
* DNSimple did support it at some point in history (we have some existing ones)
* Dynect supports creation of DNS records with Mixed-Case fqdns
* Dynect creates DNS records with "sticky" case - ie. once created in Mixed-Case it will always be mixed-case, even if DELETED, PUBLISHED and RE-CREATED
This set of conditions lead to being able to create a zone definition which attempts to create a mixed-case DNS record, but that immediately diverges state (or is considered to have diverged)
this PR downcases the fqdn...
1. when loading from API
2. when loading from YAML
the end result will be to...
1. always create DNS records with lower-case fqdns …
=> lowercase fqdns

CHANGELOG.md, lib/record_store/version.rb
bump to version 5.3.0
implements "case insensitivity" through lowercase for better support across DNS providers
=> version 5.3.0

CHANGELOG.md, lib/record_store/provider/dynect.rb, lib/record_store/version.rb
`fog-dynect` is locked to Dyn API version `3.7.0`
CAA support was not added until `3.7.6` (see https://manage.dynect.net/help/changelog.html)
This PR explicitly specifies the API version to use, overriding the version fog-dynect specifies
=> use Dyn API version 3.7.13 which actually supports CAA records

CHANGELOG.md, lib/record_store/provider/dynect.rb, lib/record_store/version.rb, record_store.gemspec, test/fixtures/vcr_cassettes/dynect_apply_changeset.yml, test/fixtures/vcr_cassettes/dynect_apply_changeset_update.yml, test/fixtures/vcr_cassettes/dynect_retrieve_current_records.yml, test/fixtures/vcr_cassettes/dynect_retrieve_current_records_no_alias.yml, test/fixtures/vcr_cassettes/dynect_zones.yml
This PR updates record_store to use fog-dynect 0.4.0 instead of overriding the Dyn API version as was previously done in #79
=> fog-dynect update

.gitignore, lib/record_store.rb, lib/record_store/provider.rb, lib/record_store/provider/ns1.rb, lib/record_store/provider/ns1/client.rb, lib/record_store/version.rb, record_store.gemspec, template/secrets.json, test/dummy/secrets.json, test/fixtures/vcr_cassettes/ns1_add_a_changeset.yml, test/fixtures/vcr_cassettes/ns1_add_alias_changeset.yml, test/fixtures/vcr_cassettes/ns1_add_caa_changeset.yml, test/fixtures/vcr_cassettes/ns1_add_changeset.yml, test/fixtures/vcr_cassettes/ns1_add_changeset_missing_zone.yml, test/fixtures/vcr_cassettes/ns1_add_cname_changeset.yml, test/fixtures/vcr_cassettes/ns1_add_multiple_changesets.yml, test/fixtures/vcr_cassettes/ns1_add_mx_changeset.yml, test/fixtures/vcr_cassettes/ns1_add_ns_changeset.yml, test/fixtures/vcr_cassettes/ns1_add_spf_changeset.yml, test/fixtures/vcr_cassettes/ns1_add_srv_changeset.yml, test/fixtures/vcr_cassettes/ns1_add_txt_changeset.yml, test/fixtures/vcr_cassettes/ns1_get_zones.yml, test/fixtures/vcr_cassettes/ns1_remove_changesets.yml, test/fixtures/vcr_cassettes/ns1_remove_record_should_not_remove_all_records_for_fqdn.yml, test/fixtures/vcr_cassettes/ns1_update_changeset.yml, test/fixtures/vcr_cassettes/ns1_update_changeset_for_fqdn_with_multiple_answers.yml, test/fixtures/vcr_cassettes/ns1_update_changeset_where_domain_doesnt_exist.yml, test/fixtures/vcr_cassettes/ns1_updating_record_ttl.yml, test/providers/ns1_test.rb, test/test_helper.rb
NS1 is not a supported DNS provider
**How will this fix it?**
- By adding a provider for NS1
**Notes**
- To record new cassettes you'll need:
- An NS1 account and API key
- The empty zone, `test.recordstore.io` in your account.
~~**Why WIP?**~~
- ~~[x] We should refine how we handle errors from the NS1 library``~~
- ~~[x] We should improve how we remove records.  Right now, removing a record will remove all records for the FQDN.~~
=> Add NS1 provider

lib/record_store/cli.rb, lib/record_store/zone.rb
Related to https://github.com/Shopify/record_store/issues/84
Remove the redundant use of Object#to_s in interpolation
=> Style: remove redundant use of Object#to_s in interpolation

lib/record_store/provider/google_cloud_dns.rb, test/providers/dnsimple_test.rb, test/providers/dynect_test.rb, test/providers/ns1_test.rb, test/zone_test.rb
Style: remove redundant curly braces around a hash parameter
=> Style: remove redundant curly braces around a hash parameter

test/changeset_test.rb, test/providers/google_cloud_dns_test.rb, test/providers/ns1_test.rb, test/zone_test.rb
Style: trailing comma in array literal
```ruby
assert_equal(
1,
Zone.filter_records(
records,
[
Zone::Config::IgnorePattern.new(type: 'CNAME'),
],
).length,
)
```
I didn't go this way because it looks very different compared to a single line of assert.
But if it's much better, I can update it later! 👍
=> Style: trailing comma in array literal

lib/record_store/record.rb
Related to #84
- protected access modifiers don't make singleton methods
=> Lint: ineffective access modifier

CHANGELOG.md, lib/record_store/version.rb, record_store.gemspec
OCI library as runtime dependency was missing 
**How does this fix it?**
Adding OCI library to the runtime dependency 
**How will I ship?**
- Merge this PR
- Have shipit it
- Release next version
**How to rollback?**
Revert the PR
=> bump up the version to 5.7.0 with OCI library

dev.yml
The currently matched version of `activesupport` appears to depend on Ruby 2.5.0.
On Ruby 2.4.3:
```
┃┃ Gem::RuntimeRequirementNotMetError: zeitwerk requires Ruby version >= 2.4.4. The current ruby version is 2.4.3.205.
┃┃ An error occurred while installing zeitwerk (2.2.1), and Bundler cannot continue.
┃┃ Make sure that `gem install zeitwerk -v '2.2.1' --source 'https://rubygems.org/'` succeeds before bundling.
┃┃ In Gemfile:
┃┃   record_store was resolved to 5.7.1, which depends on
┃┃     activemodel was resolved to 6.0.1, which depends on
┃┃       activesupport was resolved to 6.0.1, which depends on
┃┃         zeitwerk
┃
```
On Ruby 2.4.4:
```
┃┃ Gem::RuntimeRequirementNotMetError: activesupport requires Ruby version >= 2.5.0. The current ruby version is 2.4.4.296.
┃┃ An error …
```
=> Bump ruby dependency to 2.5.0

lib/record_store/provider/ns1.rb, lib/record_store/version.rb, record_store.gemspec, test/fixtures/vcr_cassettes/ns1_update_changeset_where_domain_doesnt_exist.yml, test/test_helper.rb
**Problem**
Our current approach for fetching the resource records in a zone requires:
- A GET on the target zone.  The response contains a summary of the resource record sets contained in that zone.
- These summaries missing `id`s for individual resource records.
- A GET on each resource recordset in the target zone to reveal resource records with `id`'s.
- All of these fetches are rate limited at 3rps.
- **Problem** Every record present in NS1 managed zones will slow down subsequent syncs by 0.3 seconds.
**How does this help?**
- We require resource records to be individually `id`'ed so we can compute zone updates in a provider agnostic way, then perform the actual updates across all providers using this `id`.
- As a workaround, this change will have `record_store` compute these `id` s …
=> NS1: Generate resource record ids locally

.rubocop-https---shopify-github-io-ruby-style-guide-rubocop-yml, test/test_helper.rb
Address the following deprecation errors during CI:
```
...
...
...
$ bin/rubocop --version && bin/rubocop                                                                                                         
0.77.0
Error: The `Layout/AlignArray` cop has been renamed to `Layout/ArrayAlignment`.
(obsolete configuration found in .rubocop-https---shopify-github-io-ruby-style-guide-rubocop-yml, please update it)
The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in .rubocop-https---shopify-github-io-ruby-style-guide-rubocop-yml, please update it)
The `Layout/AlignParameters` cop has been renamed to `Layout/ParameterAlignment`.
(obsolete configuration found in .rubocop-https---shopify-github-io-ruby-style-guide-rubocop-yml, please update it) …
```
=> Fix rubocop and various other CI errors

lib/record_store/provider/ns1.rb, lib/record_store/version.rb, test/fixtures/vcr_cassettes/ns1_colons_always_escaped_when_exported_from_ns1.yml, test/fixtures/vcr_cassettes/ns1_escaped_colons_maintained_when_exported_from_ns1.yml, test/providers/ns1_test.rb, test/test_helper.rb
**What's the problem**
- If a `record_store` YML file contains text resource records with rrdata containing semi-colons, when these records are pushed to DNS providers:
- Those colons (`;`) are POSTed to NS1 as escaped colons (`\;`).  This turns out to not be a problem.
- **Problem**: During a subsequent diff, those records are considered to be out of sync, because of the difference in escaping.
**Why'd's it happen?**
The NS1 provider introduces escaping when loading records, but doesn't strip the escaping when records are POSTed.
**Why do providers escape semi-colons on GET?**
- Because the API of one of the providers, Dynect, returns records with escaped semi-colons.  All other providers seem to be following this pattern to provide the rest of `record_store` normalized data.
- Just in …
=> NS1: Escape colons on download, unescape colons on upload in TXT rdata

lib/record_store/provider/ns1.rb, test/fixtures/vcr_cassettes/ns1_test_new_records_have_edns_client_subnet_disabled.yml, test/providers/ns1_test.rb
record_store doesn't support filter chains in NS1 & thus does not require ECS extensions when creating new records for this provider.
=> Disable client subnet when creating ns1 zones

lib/record_store/cli.rb, lib/record_store/version.rb, test/cli_test.rb, test/fixtures/vcr_cassettes/test_does_not_allow_removal_of_sshfp_records.yml
Spun off from #155. Do not apply any Changesets if even a single Zone is invalid.
This prevents a set of Zones from being only partially applied, which leaves records at our DNS providers in an inconsistent state.
=> Require all zones to be valid before applying any changesets

lib/record_store/record/spf.rb, test/cli_test.rb, test/record_test.rb, test/support/capture_output.rb, test/support/provider_teardown.rb, test/support/test_config.rb, test/test_helper.rb
instead of letting things spew to the terminal during test runs, this PR captures stdout and stderr
it sets the stage to do better integration testing, and also removes a one-off case where a test closes STDOUT
oh... and it adds a test for a deprecation message for SPF records (by using the new capture capability)
=> Capture output in tests

CHANGELOG.md, lib/record_store.rb, lib/record_store/cli.rb, lib/record_store/version.rb, lib/record_store/zone.rb, test/cli/info_test.rb, test/fixtures/config/dummy/zones/ignored-ns.com.yml, test/support/test_config.rb, test/zone_test.rb
This PR makes a couple of small changes to the `record-store` CLI to aid in debugging delegation issues.
1. adds an `--all` option to `record-store list` which will report ignored records as well.
2. adds a `record-store info` command to list the Providers and *actual* delegation for managed zones.
An example of `record-store info` output for one zone...
```
...
Zone: shopify.engineering
Providers:
- DNSimple
- NS1
Delegation:
- [NSRecord] shopify.engineering. 86400 IN NS dns3.p06.nsone.net.
- [NSRecord] shopify.engineering. 86400 IN NS dns4.p06.nsone.net.
- [NSRecord] shopify.engineering. 86400 IN NS ns4.dnsimple.com.
- [NSRecord] shopify.engineering. 86400 IN NS dns1.p06.nsone.net.
- [NSRecord] shopify.engineering. 86400 IN NS dns2.p06.nsone.net.
- [NSRecord] shopify.engineering. 86400 …
```
=> improved CLI support for debugging delegation

record_store.gemspec
shipit was updated to require explicit metadata to allow pushes to rubygems (in order to prevent accidentally pushing private gems)
=> fix gemspec to allow pushes to rubygems

lib/record_store/cli.rb, lib/record_store/zone.rb, test/zone_test.rb
this PR adds unit tests for authoritative nameserver lookup, and fixes the case where a domain is not delegated
=> bugfix for missing authoritative nameservers

lib/record_store/cli.rb, lib/record_store/provider.rb, test/cli/validate_authority_test.rb, test/provider_test.rb
this PR adds a `validate_authority` command to verify provider delegation to authoritative nameservers
```
Usage:
record-store validate_authority
Options:
-v, [--verbose], [--no-verbose]  # Include valid zones in output
-c, [--config=CONFIG]            # Path to config.yml
Validates that authoritative nameservers match the providers
```
example output...
```
bin/record-store validate_authority
Zone: splunkctf.io
- NS1: authoritative nameservers not found for configured provider
Zone: shopifyplus.ar
- DNSimple: authoritative nameservers not found for configured provider
- Unknown: unknown authoritative nameservers found
- a.dns.ar.
- b.dns.ar.
- c.dns.ar.
- d.dns.ar.
- e.dns.ar.
- f.dns.ar.
- ar.cctld.authdns.ripe.net.
Zone: buyable-pin.com
- NS1: authoritative nameservers not found for …
```
=> add command to validate authoritative DNS for providers

CHANGELOG.md, lib/record_store/version.rb
- add `record-store validate_authority` command to sanity check delegation [FEATURE]
- fix handling of NXDOMAIN, etc. when fetching authoritative nameservers [BUGFIX]
=> bump to version 5.10.0

lib/record_store/changeset.rb, lib/record_store/cli.rb, lib/record_store/zone.rb, record_store.gemspec, test/changeset_test.rb, test/fixtures/vcr_cassettes/gcloud_dns_apply_changeset.yml, test/fixtures/vcr_cassettes/gcloud_dns_retrieve_current_records.yml, test/fixtures/vcr_cassettes/gcloud_dns_zones.yml
similar to the addition of a `--all` option for the `list` command to include ignored records,
this PR adds support for `--all` to the `diff` command as well, to show differences between the ignored records in the zone definition, and the actual records in the provider(s)
it also makes it possible to specify which zones to diff (rather than all defined ones)
sample output...
```
$ bin/record-store diff --all kafka.shopifysvc.com
Diffing 1 zone(s)
Zone: kafka.shopifysvc.com
--------------------
Provider: DNSimple
Add:
- [NSRecord] kafka.shopifysvc.com. 3600 IN NS dns1.p07.nsone.net.
- [NSRecord] kafka.shopifysvc.com. 3600 IN NS dns2.p07.nsone.net.
- [NSRecord] kafka.shopifysvc.com. 3600 IN NS dns3.p07.nsone.net.
- [NSRecord] kafka.shopifysvc.com. 3600 IN NS dns4.p07.nsone.net. …
```
=> add option to include ignored records in diff

CHANGELOG.md, lib/record_store/version.rb
bump gem version to make `record-store diff --all` available
(bumping major version to 6 because of gem dependency bump)
=> bump version to 6.0.0

CHANGELOG.md, lib/record_store/provider/dnsimple.rb, lib/record_store/provider/dnsimple/patch_api_header.rb, lib/record_store/version.rb, test/providers/dnsimple_test.rb
Patches the DNSimple client to add API rate limiting. This follows a similar approach to how it was done for the [NS1 provider](https://github.com/Shopify/record_store/blob/master/lib/record_store/provider/ns1/patch_api_header.rb#L6-L8).
=> Add rate limiting for DNSimple provider

CHANGELOG.md, lib/record_store/zone.rb, test/zone_test.rb
this PR implements retry if an authoritative NS is unreachable
=> Handle unreachable host when looking up authority

CHANGELOG.md, lib/record_store/zone.rb
The original implementation assumed all records in the authority section were all NS records, but other record types can be present. This PR updates to filter out non-NS records.
=> handle non-NS records returned as authority

CHANGELOG.md, lib/record_store/provider/dnsimple/patch_api_header.rb, lib/record_store/provider/ns1/patch_api_header.rb, lib/record_store/provider/provider_utils/rate_limit.rb, lib/record_store/version.rb, test/providers/dnsimple_test.rb, test/providers/provider_utils/rate_limit_test.rb
This PR is to prevent Shipit from timing out because of a lack of output when waiting for the NS1 rate-limit to elapse. To do this we emit a "waiting" message `Waiting on NS1 provider` every 10 seconds to let Shipit know that we're still alive and just waiting for our rate-limit to elapse.
=> Add print when waiting for rate-limit to elapse so deployment doesn't timeout

.rubocop-https---shopify-github-io-ruby-style-guide-rubocop-yml, lib/record_store/provider.rb, lib/record_store/provider/dnsimple.rb, lib/record_store/provider/ns1.rb, lib/record_store/provider/ns1/patch_api_header.rb, lib/record_store/version.rb, test/providers/dnsimple_connection_errors_test.rb, test/providers/ns1_connection_errors_test.rb, test/test_helper.rb
- `record_store` doesn't really protect its transactions.  A failure during during a CI run in which `record_store` is run could result in inconsistencies between a `record_store` configuration and DNS providers.
- For this reason, it's important that `record_store` does not fail unnecessarily.
- Transient network problems (connection timeouts, connection resets), although rare, could cause `record_store` to fail, but can be retried if they occur during read operations.
**How does this help?**
By performing a limited number of retries where a request hits connection timeouts or connection resets.  The threshold of errors is reached when 5 connection timeouts or 5 connection resets are encountered on a single connection attempt.  These counters could be expanded as …
=> Retry read operations on connection errors

lib/record_store/provider.rb, lib/record_store/provider/dnsimple.rb, lib/record_store/record.rb, lib/record_store/version.rb, lib/record_store/zone.rb, lib/record_store/zone/config.rb, test/zone/config_test.rb, test/zone_test.rb
All providers do not behave the same way for non-empty terminal records over wildcards. For instance:
- If you have record `*.domain.example.com` that `CNAME` to `target1.example.com`
- If you create record `a.b.domain.example.com` that `CNAME` to `target2.example.com`
- Some providers (case A) will consider that `b.domain.example.com` is a `CNAME` to `target1.example.com` (using the wildcard).
- Some providers (case B) will consider that `b.domain.example.com` is an empty non-terminal, and will return `NODATA` (skipping the `CNAME`). In this case, having the `b.domain.example.com` record created is **mandatory** if you want it to resolve.
We introduce a new `non_empty_terminal_over_wildcard` configuration parameter for the zone, that will be deduced automatically from the zone if _at …
=> Add support for raising errors when an empty non terminal overrides a wildcard

lib/record_store/provider.rb, lib/record_store/version.rb, test/providers/dnsimple_connection_errors_test.rb, test/providers/ns1_connection_errors_test.rb
Remember #173 ?  It doesn't handle another type of timeout, Errno::ETIMEDOUT
**How does this fix it?**
Also retries on these errors.
=> Also retry when a timeout manifests as an Errno::ETIMEDOUT

lib/record_store/zone.rb
we were getting...
`zone.rb:270: warning: character class has '-' without escape: /^([a-zA-Z0-9-_]+\.[a-zA-Z0-9-_])\.api\.shopify\.io\.$/`
the regex does in fact have a small bug, although I can't reproduce the warning
this PR fixes the regex(es) by escaping the standalone hyphens
=> escape hyphen in regex

lib/record_store/provider.rb, lib/record_store/provider/ns1.rb, lib/record_store/provider/ns1/client.rb, lib/record_store/provider/ns1/patch_api_header.rb, lib/record_store/provider/provider_utils/waiter.rb, test/fixtures/vcr_cassettes/ns1_update_changeset_where_response_is_unparseable.yml, test/fixtures/vcr_cassettes/ns1_update_changeset_where_service_is_unavailable.yml, test/providers/ns1_connection_errors_test.rb, test/providers/ns1_test.rb
NS1 returns an HTML body with a 503 status (service unavailable). `NS1:Client` tries to parse the HTML body as a JSON, which throws an uncaught error.
Related to #179 
Create a new error type `RecordStore::Provider::ProviderUnavailableError` which is raised when NS1 returns a 503 status. If the error is raised within `RecordStore::Provider#retry_on_connection_errors`, then the connection will be retried several times.
=> Handle NS1 Unparseable Responses

record_store.gemspec, test/changeset_test.rb, test/cli_test.rb, test/providers/dnsimple_test.rb, test/providers/dynect_test.rb, test/providers/google_cloud_dns_test.rb, test/providers/ns1_test.rb, test/providers/oracle_cloud_dns_test.rb, test/zone_test.rb
rubocop [has yet to stabilize its APIs](https://github.com/rubocop-hq/rubocop#installation).
This has [time](https://travis-ci.org/github/Shopify/record_store/builds/734378288) and [time](https://travis-ci.org/github/Shopify/record_store/builds/675835977) and [time again](https://travis-ci.org/github/Shopify/record_store/builds/718783368) generated spurious CI/rubocop failures, even if the files found to be in violation were not modified in the PR.
In my view this creates needless busy work for marginal benefit. There is little value in bikeshedding over what a linting rule is called, or which rules must be enabled by default.
Let's pick one set of rules - from `rubocop-0.89.1` - and just roll with it. Once rubocop stabilizes their API we can consider bumping the version.
Also spends time …
=> Explicitly depend on rubocop-0.89.1

.rubocop-https---shopify-github-io-ruby-style-guide-rubocop-yml, record_store.gemspec
[Rubocop has released v1.0.0](https://metaredux.com/posts/2020/10/21/rubocop-1-0.html).
Thankfully there are no changes required to upgrade to this version, so let's bump the dependency now and enjoy API stability.
=> Upgrade to rubocop-1.0.0

lib/record_store/version.rb, lib/record_store/zone.rb, lib/record_store/zone/config.rb, test/zone_test.rb
- Minor bugfix where we missed one spot in the feature code for renaming `implicit_record_templates` to `implicit_records_templates` following feedback from https://github.com/Shopify/record_store/pull/185#discussion_r533545989
=> Use proper name for implicit_records_templates in Zone::Config

lib/record_store/version.rb, lib/record_store/zone.rb, lib/record_store/zone/yaml_definitions.rb, test/fixtures/config/dummy/zones/dup-keys.com.yml, test/zone_test.rb
Considers records in a zone in particular yaml file to be invalid if there are any records which have duplicate keys (which would cause the most recent definition of the key to silently clobber any previous definitions)
Considers all records in a zone across any yaml files. I don't think it's actually possible to have a conflict of this kind given that the secondary yaml files that can exist in a subdir are only for specific records though.
I still left `abstract_syntax_trees` as a plural to map the filename to the ast, though, because it's more technically correct to consider a zone as made up of at least but not necessarily exactly 1 yaml document.
=> add validation to zone to detect duplicate record keys

CHANGELOG.md, lib/record_store/version.rb, lib/record_store/zone/config/implicit_record_template.rb
Currently, you see nil errors when any of the optional filters are not present (`except_record`  or `conflict_with`). This fix initializes those variables if any of those filters are not present in the template file.
=> Bug: Initialize filters if they don't exist in the template file

lib/record_store.rb, lib/record_store/cli.rb, template/zones/dynect.example.com.yml
Fixes issues with `./bin/console` and `/bin/record-store list` due to (I assume) some past directory reorganizing and small code shuffles that happened without tests to recognize it caused breakages in these utility scripts.
=> fix out-of-date console/cli

lib/record_store/zone.rb
Had a fun error running tests just once - seems very intermittent:
```
2) Error:
ZoneTest#test_modified_returns_all_zones_with_changes:
NoMethodError: undefined method `unchanged?' for nil:NilClass
record_store/lib/record_store/zone.rb:66:in `block (2 levels) in modified'
```
I can't be 100% sure what I'm doing addresses the issue, but it seems likely since ignoring race conditions I'm not sure how else you'd end up with a nil `current_zone`.
Also just made it one lock/unlock action on the mutex
=> account for race in mutex usage

CHANGELOG.md, lib/record_store/version.rb
This PR releases record_store gem version 6.5.3 to add support for shadowed record detection. 
Related to https://github.com/Shopify/record_store/pull/191
=> Bump gem version

lib/record_store/cli.rb
Reverts the path change, introduced in [192](https://github.com/Shopify/record_store/pull/192/files#diff-baf2a5717b6a8c0a807c936232471e4f13dc4c09c93c07fcb45c2b7bd6495af0R10) as it seems to be blocking deploys.
=> Revert path change

.rubocop.yml, lib/record_store.rb, lib/record_store/cli.rb, lib/record_store/provider.rb, lib/record_store/provider/dnsimple.rb, lib/record_store/provider/dynect.rb, lib/record_store/provider/google_cloud_dns.rb, lib/record_store/provider/ns1.rb, lib/record_store/zone.rb, lib/record_store/zone/config/implicit_record_template.rb, lib/record_store/zone/yaml_definitions.rb, record_store.gemspec
Rubocop isn't working on master branch and it's because the config had changed but this repo is still configured to use the old config, resulting in a `404 "Not Found" while downloading remote config file ...` error. This PR updates it and makes rubocop runnable again.
Please note that this change generated a lot of `Correctable` offenses:
`61 files inspected, 1701 offenses detected, 1692 offenses auto-correctable`
For this, I added some custom cops to ignore a lot of the errors and then autocorrected the remaining 15. 
I'm definitely flexible when it comes to which cops to enable/disable but wanted to avoid changing too many files at once. 😄
=> Update Rubocop config

CHANGELOG.md, lib/record_store/provider/dnsimple.rb, lib/record_store/provider/dnsimple/patch_request_error_to_include_errors.rb, lib/record_store/version.rb, test/fixtures/vcr_cassettes/dnsimple_test_non_validation_errors_exclude_details.yml, test/fixtures/vcr_cassettes/dnsimple_test_validation_errors_include_details.yml, test/providers/dnsimple_test.rb
When the DNSimple API returns validation errors, although the type of the API error is included in exceptions (`Validation failed`), the details of the error are omitted.
For example, if we somehow attempted to put a zone into an inconsistent state (and this passed through the validations in descendants of `RecordStore::Record`) an exception with the following message would be emitted by `record_store`:
```
Dnsimple::RequestError: Validation failed
```
This doesn't give us much to go on as far as how to do these validations in `RecordStore` itself.
**How does this fix it?**
It appears as though the DNSimple API includes these details in the `errors` field of responses.  This change simply ensures that these details are included in exceptions.
So, instead of the …
=> Emit DNSimple API error details

lib/record_store/version.rb, lib/record_store/zone.rb
I found a reference to ruby 2.7 deprecating automatic conversion of a hash to kwargs, but can't find a changelog reference that says it was fully removed at some point between 2.7 and 3.1
Regardless: I can say this is broken on ruby 3.1 because it wants kwargs, and doing this fixes it.
=> it seems hash to kwargs is not implied any more

.github/workflows/ci.yml, lib/record_store/version.rb, record_store.gemspec, test/zone/config_test.rb, test/zone_test.rb
Needed to bump one dependency which had some deprecated use of URI, needed to account for some cases where now-removed behaviour of implicit hash to kwargs conversion happened.
=> Update to ruby 3.1

CHANGELOG.md, lib/record_store/cli.rb, lib/record_store/version.rb
Recently had an ugly error in `record-store` [here](https://buildkite.com/shopify/record-store/builds/9961#018236c1-57ba-4bd5-b54f-02494bb22ce0)
This is a quick and dirty fix, but I'm not sure it's worth trying hard given the underway plans to drop record store anyway.
=> account for model validation errors in output

CHANGELOG.md, lib/record_store/provider/ns1.rb, lib/record_store/version.rb
`from_short_api_answer` failed to cast to integers the SRV values. Other api answer parsers did do it, which led to ID mismatches while trying to update a SRV record.
This fix was tested in an application that used this gem manually to unblock the deployment pipeline.
=> Fix handling of SRV records in NS1

.github/dependabot.yml, .github/workflows/stale-action-handling.yml
Adding dependabot config with [dependabot groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) so weekly version updates for minor and patch versions will be in one single PR. Major updates will be separate, in individual PRs.
Also adding the [github stale action](https://github.com/actions/stale), to close stale issues and PRs.
=> Adding stale and dependabot

CHANGELOG.md, lib/record_store/record.rb, lib/record_store/version.rb, test/record_test.rb
Fix #240 
We've hit an issue where a Google Certificate Manager requires creating a record like this:
`_acme-challenge_fl6lu2jzu7jamg5z.bcldb-integration-dev.shopifysvc.com.`.
Unfortunately that's not currently allowed by record_store as it fails validation if there's an underscore in the middle of the FQDN.
This PR relaxes that requirement.
=> Allow underscores in the middle of CNAMEs

test/cli_test.rb, test/providers/cloudflare_connection_errors_test.rb, test/providers/cloudflare_test.rb
The Cloudflare provider should be feature equivalent with the NS1 and DNSimple providers. As a first step towards achieving this equivalence, I have refactored the NS1 and DNSimple tests to also apply to the Cloudflare provider, which is currently pending implementation.
As the implementation progresses, tests may be added or removed based on the actual functionalities and requirements of the Cloudflare API.
All tests are set to be skipped at present.
=> Implement Initial Test Suite for Cloudflare Provider

CHANGELOG.md, lib/record_store/provider/cloudflare.rb, lib/record_store/version.rb, test/providers/cloudflare_test.rb
We weren't getting rdata for SRV records correctly 
Update the code to get `record.rdata`
I also bumped the version of record_store from 8.0.2 to 8.0.3
=> Resolve srv record bug
