lib/record_store/zone.rb

**Problem**
Before we'd be creating a thread for every zone. This would cause DynECT fetch jobs collide raising errors:
```
"{\"status\": \"failure\", \"data\": {}, \"job_id\": 2950870089, \"msgs\": [{\"INFO\": \"token: This session already has a job running\", \"SOURCE\": \"API-B\", \"ERR_CD\": \"OPERATION_FAILED\", \"LVL\": \"ERROR\"}]}"
```
**Solution**
Use a thread pool for fetching zones with failure handling when fetch jobs collide.
r: @stonith @dwradcliffe @marc-barry

Cap Zone.modified thread pool size

---

README.md
Rakefile
lib/record_store/cli.rb
template/bin/test
template/config.yml

turns out this isn't very useful and having the list of zones in the config is just confusing
@es @stonith

remove validate_all_present command

---

lib/record_store/record.rb

remove backward compatibility for ALIAS using cname

---

lib/record_store/version.rb

I forgot to bump version at https://github.com/Shopify/record_store/pull/30.
@Shopify/traffic

bump version

---

Gemfile
Gemfile.lock
lib/record_store/version.rb

* Move fog-dynect to 0.2.0
* Update other gems

Move to fog-dynect 0.2.0 and update other gems

---

lib/record_store/cli.rb
lib/record_store/provider.rb
lib/record_store/provider/dynect.rb
lib/record_store/record/a.rb
lib/record_store/record/aaaa.rb
test/test_helper.rb
test/zone_test.rb

This PR contains the fix to some Ruby warnings and deprecations.

Fix some Ruby warnings and deprecations

---

Gemfile
Gemfile.lock
lib/record_store/version.rb
record_store.gemspec

Add missing gems to the runtime dependencies in the gemspec.

Fix runtime dependencies in the gemspec

---

README.md
template/secrets.json

Update the documentation for using the DNSimple v2 API.

Update README for the DNSimple API v2

---

CHANGELOG.md
lib/record_store/record/caa.rb
lib/record_store/version.rb
test/record_test.rb

followup to #77
fix case-sensitivity for CAA values

case insensitive regex for caa

---

lib/record_store/changeset.rb
lib/record_store/provider.rb
lib/record_store/record.rb
lib/record_store/zone.rb

Related to https://github.com/Shopify/record_store/issues/84
Remove the redundant 'self' in the code.

Style: remove redundant 'self'

---

lib/record_store/record/caa.rb
lib/record_store/zone.rb
test/changeset_test.rb
test/zone/config_test.rb
test/zone_test.rb

Layout: space inside hash literal braces

Layout: space inside hash literal braces

---

lib/record_store/provider/ns1.rb
lib/record_store/record.rb
lib/record_store/record/mx.rb
lib/record_store/zone/config.rb
test/providers/dynect_test.rb
test/record_test.rb
test/test_helper.rb
test/zone_test.rb

**Style: trailing comma in hash literal**
Put a comma after the last item of a multiline hash.

Style: trailing comma in hash literal

---

lib/record_store/changeset.rb
lib/record_store/provider/ns1.rb
test/changeset_test.rb
test/zone_test.rb

**Layout: space before block braces**
Space missing to the left of {.

Layout: space before block braces

---

lib/record_store/changeset.rb

Style/Proc: Use proc instead of Proc.new.

Style: proc

---

lib/record_store/cli.rb

**Style: zero length predicate**
Use !empty? instead of size > 0.

Style: zero length predicate

---

lib/record_store/zone/yaml_definitions.rb
test/changeset_test.rb
test/providers/ns1_test.rb
test/zone/config_test.rb
test/zone_test.rb

**Layout: space inside block braces**
Space between { and | missing.

Layout: space inside block braces

---

lib/record_store/provider/ns1.rb

Style: update operator || instead of or

Style: update operator || instead of or

---

lib/record_store/record/caa.rb

Style: class check

---

lib/record_store/zone.rb

Style: update using ! instead of not

Style: update using ! instead of not

---

test/providers/ns1_test.rb

Related to #84
Layout: space around keyword
- space after keyword do is missing

Layout: space around keyword

---

test/test_helper.rb

Related to #84
Style: preferred hash methods
- use key? instead of has_key?

Style: preferred hash methods

---

lib/record_store/record.rb

Layout: extra spacing

---

lib/record_store/zone.rb
test/providers/ns1_test.rb
test/test_helper.rb

Layout: trailing white space

---

lib/record_store/cli.rb
lib/record_store/zone.rb

Related to #84
- use next to skip iteration

Style: next

---

record_store.gemspec
test/cli_test.rb

Related to #84
- use %x around command string

Style: command literal

---

lib/record_store/provider/dnsimple.rb

Related to #84
- use to_s over string interpolation

Style: unneeded interpolation

---

lib/record_store/provider/dynect.rb
lib/record_store/provider/ns1/client.rb
test/changeset_test.rb
test/providers/dnsimple_test.rb
test/providers/dynect_test.rb
test/providers/google_cloud_dns_test.rb
test/providers/ns1_test.rb
test/test_helper.rb
test/zone_test.rb

Related to #84
- use parenthese for method calls with arguments

Style: method call with args parentheses

---

lib/record_store/changeset.rb
lib/record_store/zone.rb
test/providers/ns1_test.rb

Style: avoid parallel assignment

---

test/providers/ns1_test.rb

Layout: indentation width

---

lib/record_store/zone.rb

Layout: case indentation

---

lib/record_store/cli.rb
lib/record_store/zone/yaml_definitions.rb
test/zone/config_test.rb
test/zone_test.rb

Style: symbol proc

---

lib/record_store/cli.rb

Style: redundant begin block

---

lib/record_store/provider.rb

Related to #84
- redundant else-clause

Style: empty else

---

record_store.gemspec

Layout: empty lines

---

test/changeset_test.rb
test/providers/dynect_test.rb
test/providers/google_cloud_dns_test.rb

Layout: multiline method call brace layout

---

test/providers/google_cloud_dns_test.rb

Layout: closing parenthesis indentation

---

lib/record_store/cli.rb

Style: command literal (additional)

---

lib/record_store/record/a.rb
lib/record_store/record/aaaa.rb

Style: redundant begin block #2

---

lib/record_store/changeset.rb

Layout: space inside block braces & Style: empty literal

---

record_store.gemspec

Style: regex literal

---

lib/record_store/provider/google_cloud_dns.rb

Layout: empty lines #2

---

lib/record_store/cli.rb

Style: no unless with else

---

bin/console
bin/record-store
template/bin/record-store

Related to #48
- prefer $LOAD_PATH over $:

Style: special global vars

---

lib/record_store/provider/ns1/client.rb

Style: empty lines around module body

---

test/zone_test.rb

Related to #84
- no space inside array brackets

Layout: space inside array literal brackets

---

test/zone_test.rb

Lint: ambiguous regex literal

---

lib/record_store/record.rb

Related to #84 
- surrounding space missing

Layout: space around equals in parameter default

---

test/zone_test.rb

Layout: align array

---

test/zone_test.rb

Layout: indentation consistency

---

lib/record_store/zone/yaml_definitions.rb

Lint: handle exceptions

---

test/test_helper.rb

Layout: align hash

---

test/record_test.rb

Layout: space around operators

---

test/zone/config_test.rb

Lint: implicit string concatenation

---

bin/console

Related to #84
- remove debugger entry point

Lint: debugger

---

lib/record_store/provider.rb
lib/record_store/provider/google_cloud_dns.rb
lib/record_store/provider/ns1.rb
lib/record_store/zone.rb

Lint: unused method argument

---

lib/record_store/provider/dynect.rb

Lint: unused block argument

---

lib/record_store.rb
lib/record_store/cli.rb
lib/record_store/provider/dynect.rb
lib/record_store/provider/ns1.rb
lib/record_store/record/alias.rb
lib/record_store/record/caa.rb
lib/record_store/record/cname.rb
lib/record_store/record/mx.rb
lib/record_store/record/ns.rb
lib/record_store/record/srv.rb
lib/record_store/zone.rb
record_store.gemspec
test/providers/ns1_test.rb
test/record_test.rb
test/test_helper.rb
test/zone_test.rb

Related to #84
- line is too long (over 120)

Metrics: line length

---

lib/record_store/provider.rb

Could cause an error if there's like `test.dnsimple.com`.
**How does this fix it?**
Updated RegEx
**How to rollback?**
Revert this PR

update leading dot for rest of providers

---

CHANGELOG.md

updates changelog to include details from https://github.com/Shopify/record_store/pull/81

Update Changelog for previous change

---

.rubocop-https---shopify-github-io-ruby-style-guide-rubocop-yml
CHANGELOG.md
lib/record_store/provider/ns1.rb
lib/record_store/version.rb
test/fixtures/vcr_cassettes/ns1_very_long_txt_record_more_than_255_chars.yml
test/providers/ns1_test.rb

There has been an issue this week-end related to that, as now NS1 is doing the split themselves:
```
Sat 29 Feb 2020 15:10:00 EST → dig @dns1.p06.nsone.net. TXT shops.shopify.com
; <<>> DiG 9.10.6 <<>> @dns1.p06.nsone.net. TXT shops.shopify.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25099
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;shops.shopify.com.		IN	TXT
;; ANSWER SECTION:
shops.shopify.com.	3600	IN	TXT	"\"v=spf1 ip4:35.184.170.228 ip4:35.184.254.92 ip4:35.185.32.98 ip4:35.188.30.230 ip4:35.190.163.94 ip4:35.196.108.190 ip4:35.203.111.169 ip4:35.203.117.150 …
```

ns1: do not split long TXT records as NS1 is now doing it

---

CHANGELOG.md
lib/record_store/version.rb

cut the new release once the other PRs are merged...
#169
#170 
#168

version 6.1.0

---

.travis.yml
dev.yml

bumping the CI ruby (and the development one) to 2.6.4

ruby 2.6.4

---

.github/workflows/ci.yml
lib/record_store/version.rb
lib/record_store/zone.rb
lib/record_store/zone/yaml_definitions.rb
test/fixtures/config/dummy/zones/dup-keys.com.yml
test/zone_test.rb

Redo of https://github.com/Shopify/record_store/pull/187 as Travis CI is not linked anymore

add validation to zone to detect duplicate record keys

---

lib/record_store/zone.rb

https://github.com/Shopify/record_store/pull/193#issuecomment-923095441

restore broken up mutex syncs to allow change check outside critical section

---

CHANGELOG.md
lib/record_store/version.rb

This PR increments the gem version to pickup changes in the build pipeline.

Bump version for build path change

---

lib/record_store/provider/dnsimple.rb

This fixes the issue at https://github.com/Shopify/record_store/issues/220

Change update_record to update_zone_record for DNSimple

---

lib/record_store/provider/cloudflare/client.rb
lib/record_store/provider/cloudflare/configuration.rb
lib/record_store/provider/cloudflare/response.rb

Copies basic components of the cloudflare client using internally as a gem.
This is just the config, response and `Net::HTTP` related code.

Create initial Cloudflare client

---

CHANGELOG.md
README.md
lib/record_store/provider.rb
lib/record_store/provider/cloudflare.rb
lib/record_store/version.rb

When reviewing please look at the error I catch in `lib/record_store/provider/cloudflare.rb` and its design limitation that I describe in the README.

7.1.0 Release

---

CHANGELOG.md
lib/record_store/version.rb

PR to bump record_store gem version from 8.0.0 to 8.0.1

Bump version from 8.0.0 to 8.0.1
